#footprint: [ [0.181, -0.128], [0.181, 0.128], [-0.181, 0.128], [-0.181, -0.128] ]
footprint: [ [0.121, -0.108], [0.121, 0.108], [-0.121, 0.108], [-0.121, -0.108] ]
#footprint: [ [0.151, -0.118], [0.151, 0.118], [-0.151, 0.118], [-0.151, -0.118] ]

obstacle_layer:
  enabled: true
  combination_method: 1
  track_unknown_space: true
  obstacle_range: 2.0
  raytrace_range: 2.0
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: laser_frame,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    inf_is_valid: true
  }
 
inflation_layer:
  enabled: true
  cost_scaling_factor: 5.0
  inflation_radius: 0.2  # 0.2
#0.15
 
static_layer:
  enabled: true